### ISSUE TITLE
Pascal-50s

### ISSUE THREAD

**Issue by namin-an** [keio-smilab24/Polos#6]
Hello,

I tried to download the pascal-50s dataset using the original link you provided, but I cannot access the link somehow.
[https://vrama91.github.io/cider/](https://vrama91.github.io/cider/)

**Comment by YuigaWada** [comment]
Hi,

It seems the URL has changed due to a username update on GitHub (https://ramavedantam.com/cider/). 

The `.mat` files cannot be downloaded now, so I've prepared a mirror for you to use. Please use the following link: https://drive.google.com/drive/folders/1tEIBaZS8elfNeFPF2y72HVS80Kjs4Jib

**Comment by namin-an** [comment]
Thank you so much! :)
